name: Test deployment workflow

on: [push]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test echo
        run: echo "Hola Mundo - Build"
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test echo
        run: echo "Hola Mundo - Test"